# Generated by Django 5.0 on 2024-01-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='headline',
            name='url',
            field=models.URLField(),
        ),
    ]
